[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
staking = "3zvTUf8MUCdMEztg6JY66Ypf4W8Uk9Z9PjRkfiT3SpFN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/apollo/pl-staking/staking-veer/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
